---
- name: Install the dependencies for compiling and installing the Git binaries
  yum: pkg={{ item }}
  with_items:
    - curl-devel
    - expat-devel
    - gettext-devel
    - openssl-devel
    - perl-devel
    - zlib-devel
